### ISSUE TITLE
Typo in repository description

### ISSUE THREAD

**Issue by neenaoffline** [SUPERAndroidAnalyzer/super#10]
Hi,
I think there's a typo in the Github description.

<img width="268" alt="screen shot 2016-07-05 at 10 59 36 am" src="https://cloud.githubusercontent.com/assets/303535/16574735/c2e092fa-429f-11e6-96c2-f804fd9be1ad.png">

Analizer should be Analyzer.

**Comment by Razican** [comment]
Thanks @neenaoffline!!!
