### ISSUE TITLE
How to install the app

### ISSUE THREAD

**Issue by pentagramz** [SUPERAndroidAnalyzer/super#102]
I installed using dpkg , but i can't see the super binary in debian
Please help

**Comment by Razican** [comment]
@pentagramz The binary should be in your `PATH`. What happens if you run `super -h` in your terminal?

**Comment by pentagramz** [comment]
![super](https://cloud.githubusercontent.com/assets/7072014/22680668/3ccfef2c-ed2f-11e6-9e2f-493f040d6f3a.PNG)

**Comment by pentagramz** [comment]
I just installed super

**Comment by pentagramz** [comment]
I cant see...binary

**Comment by pentagramz** [comment]
I am using debian
![tamer](https://cloud.githubusercontent.com/assets/7072014/22680722/808ccfb4-ed2f-11e6-80e9-1a1106984313.PNG)

**Comment by pentagramz** [comment]
ok the tool is working fine now thanks

**Comment by Razican** [comment]
Simply run `which super` to know where the binary was installed, and `super -h` to start using it. The binary is never on the same folder as the instalation folder in Linux, but you can use it as if it was everywhere once installed by running it. Again, `super -h` and you'll get a list of options.
