### ISSUE TITLE
where can I find SUPER in MAC OSX?

### ISSUE THREAD

**Issue by DARKTEMPLE9** [SUPERAndroidAnalyzer/super#105]
I try to download install pkg from https://github.com/SUPERAndroidAnalyzer/super/releases/download/0.3.0/super-0.3.0-macosx-x86_64.pkg. However it does not work. Anyone can help me?
Thanks

**Comment by SergioD0l** [comment]
Hi @DARKTEMPLE9, the problem takes place when you try to install the pkg or while you are executing SUPER? we need to know what is the problem exactly. 
Regards.

**Comment by DARKTEMPLE9** [comment]
Sorry about my poor english. In fact, the problem is that I cannot download the pkg from https://github.com/SUPERAndroidAnalyzer/super/releases/download/0.3.0/super-0.3.0-macosx-x86_64.pkg.  It seems the address is invalid.

**Comment by Razican** [comment]
Sorry about that, the link is now fixed in the web page. The proper link is https://github.com/SUPERAndroidAnalyzer/super/releases/download/0.3.0/super_0.3.0_macosx-x86_64.pkg
