### ISSUE TITLE
Consider changing namespace

### ISSUE THREAD

**Issue by gnieto** [SUPERAndroidAnalyzer/super#107]
I know that this may be controversial, but the current namespace of the application is `super`, which is a reserved word in Rust. This makes impossible to create integration tests on the test folder, as Rust is unable to parse the fail.

An example can be found here: https://github.com/gnieto/super/compare/bc3d917987e509fe2021182055bf2ba236d47ca4...failingTest

The error when running `cargo test` is:
```
error: expected identifier, found keyword `super`
 --> tests/integration_test.rs:1:14
  |
1 | extern crate super;
  |              ^^^^^

error: aborting due to previous error
```

**Comment by Razican** [comment]
We had some issues integrating the package with Debian too, and it's true that in general `super` is a too common word. We are considering changing it to `super-analyzer`, which would be imported as `super_analyzer`. Still nothing has been decided, though.

**Comment by Razican** [comment]
@gnieto, just curious, why would you need to import a binary crate? Most of the modules (if not all) will be private, so there is not much to test with integration tests.

**Comment by gnieto** [comment]
Mmm you are right. I don't remember how I faced this issue.
Anyway, I think that using a reserved word can be an issue in the future.

**Comment by Razican** [comment]
This has been implemented.
