### ISSUE TITLE
Add usage documentation on README

### ISSUE THREAD

**Issue by vrinek** [SUPERAndroidAnalyzer/super#11]
It would be nice to have some guidelines on how to use this on the README. I'm thinking of simple steps like "install, config, compile, download apk, run".

**Comment by Razican** [comment]
Sure! thanks for the tip, we'll be adding that ASAP :)

**Comment by Razican** [comment]
We should also add contribution guidelines to the README, or at least the link to the contributing.md.

**Comment by Razican** [comment]
This has been done, if you need further instructions, @vrinek, don't hesitate to contact us, in this same issue, if you want :)

**Comment by vrinek** [comment]
Looks great! Thanks! 😄
