### ISSUE TITLE
Use serde for configuration parsing

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#117]
Configuration should be parsed using `serde` deserialization for the `toml` crate, which would remove a lot of code from our repository, making it more maintainable.

**Comment by gnieto** [comment]
I've been working a little bit on this issue and I just realized that when decoding with `serde`, once some of the fields has an incorrect type (for example, threads = "string") it stops decoding and returns an error (so no further field is read).

The current code, for each field it has an incorrect input, it is printing a warning and keeps deserializing other fields, which is a distinct behaviour than the proposed change.

I've been checking if there's some options on serde to keep decoding if it founds an error, but I didn't found anything.

**Comment by Razican** [comment]
This should be closed, let me know if there is something left.
