### ISSUE TITLE
Citing and i need a tip

### ISSUE THREAD

**Issue by AjaxFB** [SUPERAndroidAnalyzer/super#138]
As the authors of the project wish to be quoted in articles and what they think of my approach to get as much information out of the program.

```
for /f %F in ('dir <samples directory> /b /a-d') do 
super.exe <samples directory>\%F" 
&&
 rename results %F
```

**Comment by Razican** [comment]
Hi! not sure if I understood the issue, the script you provided enables checking multiple APKs in a directory, but SUPER already provides a flag to do this: `--test-all` or `-a`, and adding a path, it will get all *.apk* files there and test them.

What did you mean by quoting the authors of the project in articles?

**Comment by Razican** [comment]
I will close this issue due to lack of response, but please, feel free to comment again, and I will re-open it.
