### ISSUE TITLE
Reduce rules detection related to decompiler

### ISSUE THREAD

**Issue by Chuky9** [SUPERAndroidAnalyzer/super#14]
As we are not sure if the decompiler process is reliable as some information is missing (Try and catch structures, for loops, while loops) we should remove those rules until we find how the decompiler process works.

**Comment by Razican** [comment]
We should in any case check how valid those alerts are.

**Comment by Chuky9** [comment]
At the moment the rules related to "Empty catches" and "Empty Try and Catch" structures have been temporaly removed.

**Comment by Razican** [comment]
I will close this and open an issue for testing those rules.
