### ISSUE TITLE
Improve URL disclosure regex to avoid content://

### ISSUE THREAD

**Issue by Br1oP** [SUPERAndroidAnalyzer/super#15]
At this moment, URLs that start by "content://" are detected by this rule. This should not happen since we do not want to include the Content Provider URLs as URL disclosure.

It is not so easy as using a Whitelist since the matching part is not the "content://" but the URL that comes after it.

**Comment by Razican** [comment]
Maybe we could check somehow with forward/backward checks? @SUPERAndroidAnalyzer/rules

**Comment by Razican** [comment]
Should this be a bug or an enhancement, @Br1oP? BTW, we have a mismatch between the milestone and the project. Do we want this in 0.1.0? Does it have enough priority? maybe 0.2.0 could be fair enough.

**Comment by Chuky9** [comment]
I will work on that improving both rule detection and forwardcheck. If I am able to achieve something consistent, I will set that for the realease otherwise It will be ready for the next version.

**Comment by Chuky9** [comment]
Issue solved! As we agreed URL rule detection will be less generic restricting its content to the following structure:
"http(s)|ftp(s)://_"
or
"www._"
