### ISSUE TITLE
Expose Data Structures in Javascript 

### ISSUE THREAD

**Issue by pwn0rz** [SUPERAndroidAnalyzer/super#180]
Hi guys, this project is very interesting. And I wonder whether is this possible to **exposed the common used data struct and interface** in **Javascript API**, so that we can write rules and explore it more extensibly, making it powerful like Frida but still statically.

There is a great wheel called `rusty_v8`, which might be helpful

**Comment by Razican** [comment]
Hi, the idea behind SUPER is specifically avoid using non-native code, and avoid interpreters (we already have Java based analyzers). So we decided to use Rust.

Nevertheless, you can extend the rules by modifying the `rules.json` file included with the release. Each rule is a JSON object like this one:

```json
{
    "regex": "telephony\\.TelephonyManager ",
	"permissions": [
        "android.permission.WRITE_EXTERNAL_STORAGE"
    ],
	"whitelist": [
        "schemas.android.com",
        "www.w3.org"
    ],
    "forward_check": "getDeviceId\\s*\\(",
    "criticality": "warning",
    "label": "Get Device ID",
    "description": "The application is recording the device ID (IMEI). This process might be performed without the user's knowledge.",
    "include_file_regex": ".java$"
}
```

Where `permissions`, `whitelist`, `forward_check` and `include_file_regex` are optional. The `regex` is a regular expression used to find a potential vulnerability, the `whitelist` will whitelist potential results of the regex that might be false positives (it's an exception list). The `permissions` list will include a list of permissions that must be present for this to become a vulnerability.

Then, the `forward_check` is an extra regex that will make sure that the vulnerability will only show if the file also matches that file. This is for example used to check if the file is importing a particular vulnerable package.

Then, the `criticality` assigns a criticality level to the vulnerability, which can be one of `critical`, `high`, `warning` or `low`, and the description will be what we show in the report explaining the vulnerability.

Finally, you can add a regular expression that will select in which files the rule applies. This is usually done to not apply JavaScript rules in XML source files, and the other way around, but you can use it to find vulnerabilities in a file with a given name, for example.
