### ISSUE TITLE
SVG logo

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#27]
The logo should be SVG so that we can used in the required resolution.

**Comment by KrishAmal** [comment]
Hey , i would like to help . The logo you are reffering is [this one](https://github.com/SUPERAndroidAnalyzer/super/blob/master/templates/super/img/logo.png) , right ?
A quality SVG version of the logo comes around at 500KB , is that okay?

**Comment by Razican** [comment]
It's that logo, yes, but the idea is to make it much smaller (at most 40kB). We started with something but we didn't have too much time (or experience) to continue with it. I attach you our progress.

[super-logo.zip](https://github.com/SUPERAndroidAnalyzer/super/files/1381643/super-logo.zip)

The idea is that it should have transparent background and it should more or less have the appearance of the current logo. Does not need to be  copy of it, but it should respect its idea.

**Comment by KrishAmal** [comment]
Yeah Sure , working on it.

**Comment by KrishAmal** [comment]
@Razican how's this ?
It has transparent background as you intended and is less than 40kB.
And where should i place the SVG in the repo , is it `super/templates/super/img/` itself ?
![logovec](https://user-images.githubusercontent.com/4433284/31573963-2aa3ba36-b0e3-11e7-84a8-13ac49665850.png)

**Comment by Razican** [comment]
Hi! The logo looks amazing! :)

It should go to `templates/super/img/logo.svg` and `templates/super/img/logo.png` should be removed. There are also 3 places where the path must be modified:

 - [`Cargo.toml` line 107](https://github.com/SUPERAndroidAnalyzer/super/blob/622170b326d0bb78f61e18242f0476521917b997/Cargo.toml#L107)
 - [`Readme.md` line 7](https://github.com/SUPERAndroidAnalyzer/super/blob/7fa9b39d4c8b3017d18ffff89ab9ad44a1eb9609/README.md)
 - [`templates/super/report.hbs` line 12](https://github.com/SUPERAndroidAnalyzer/super/blob/c88704a20942a22636ff2bd5be285176c1ed3af3/templates/super/report.hbs#L12)

Please, make a pull request and we will merge the logo. Thank you for your great work!

**Comment by KrishAmal** [comment]
My pleasure :-D
