### ISSUE TITLE
Separate regex by file type

### ISSUE THREAD

**Issue by Br1oP** [SUPERAndroidAnalyzer/super#34]
At this moment, all regex execute over all files. It would be nice to separate the regex rules by what are they supposed to do. This way the regex analysis would be much more efficient. It could be something like this:
- Source code regex (.java)
- XML regex
- Manifest regex

This can be done adding a new attribute in the rules, it shouldn't be hard.

**Comment by Razican** [comment]
I'm thinking in two regexes: `include_files` and `exclude_files`. By default we would include all files and not exclude.

**Comment by Razican** [comment]
Nominating this for 0.2.0, do you agree, @SUPERAndroidAnalyzer/coders?

**Comment by Chuky9** [comment]
Let's better move it for 0.3.0

**Comment by gnieto** [comment]
If nobody is working on this, I can do it

**Comment by Br1oP** [comment]
@gnieto Sure, feel free to take it :)

**Comment by Razican** [comment]
Implemented in #100.
