### ISSUE TITLE
Coloring errors

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#41]
We currently have some coloring errors in the console, this should be fixed for the next version (or hopefully, if it's really easy to fix, for 0.1.0.

An example:
![screenshot](https://cloud.githubusercontent.com/assets/597469/18948477/78c56868-8637-11e6-9ab1-f29895a72dfc.png)

**Comment by pocket7878** [comment]
Is there any minimum example to reproduce this error?

**Comment by Br1oP** [comment]
Hello, @pocket7878. I just made a simple example to reproduce the error. This is the code:

```
extern crate colored;

use colored::*;

fn main() {
    let world = "world".bold();
    let hello_world = format!("Hello, {}!", world);
    println!("{}", hello_world);
    let hello_world = format!("Hello, {}!lalalala", world).red();
    println!("{}", hello_world);
}
```

These are the results:

![error](https://cloud.githubusercontent.com/assets/12952081/19368106/b9a1236e-919e-11e6-974d-1d6ac76d9d83.png)

As you see, when you mix bold + colour, the colouring is not working correctly. It should colour the whole sentence but it stops at the exclamation mark.

**Comment by Razican** [comment]
I reported the issue in upstream.

It might be solved using [`termion`](https://crates.io/crates/termion) ([tutorial](https://ticki.github.io/blog/making-terminal-applications-in-rust-with-termion/)), since it seems an upstream issue. If not, we might need to modify our printing system, maybe creating our own printing library.

**Comment by mackwic** [comment]
Thanks for the bug report. Please update to colored 1.3.1 which fixes the problem as the tests, and the example show (you can run `cargo run --example=nested_colors` to see @Br1oP's example passing).

If you have any issue or suggestion to make colored better, don't hesitate to submit an issue. Have a great day

Ref PR: https://github.com/mackwic/colored/pull/12

**Comment by Br1oP** [comment]
Cool, it works great now!

I'm closing this issue, thx.

**Comment by Razican** [comment]
This has been reopened in upstream, seems that we still have the problem: [colored/#11](https://github.com/mackwic/colored/issues/11)

**Comment by mackwic** [comment]
Again, thank you for the bug report. It should be ok, now 👍

**Comment by mackwic** [comment]
(please update to 1.3.2 by the way)
