### ISSUE TITLE
Including "test_all" functionality into program core

### ISSUE THREAD

**Issue by Chuky9** [SUPERAndroidAnalyzer/super#44]
We are using an script to analyze all the apks located in _/downloads_. We should consider to add this functionality as an option flag during program execution. Also a brief explanation of its usage would be requiered. What do you think?

**Comment by Razican** [comment]
I think it's fine for 0.2.0 (at least for now).

**Comment by Razican** [comment]
We will need to use [`std::fs::ReadDir`](https://doc.rust-lang.org/std/fs/struct.ReadDir.html) to read the `downloads` dir, and for each _.apk_ file run all the suite.

We will also need to modify the `clap` call in [`src/main.rs#L324`](https://github.com/SUPERAndroidAnalyzer/super/blob/develop/src/main.rs#L324) to add a `--test-all` option that is incompatible with the `<package>` argument, an we would need to specify that, the same way we do it with `--quiet` and `--verbose`.

**Comment by Razican** [comment]
This can use the [`required_unless()`](https://docs.rs/clap/2.14.0/clap/struct.Arg.html#method.required_unless) method of [`clap::Arg`](https://docs.rs/clap/2.14.0/clap/struct.Arg.html).
