### ISSUE TITLE
Add an `--open` option to automathically open reports

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#46]
Having a command line option such as `--open` (the same way as in `cargo doc --open`) to open the HTML report once generated would be really useful, and I think it wouldn't take much.

It would be as simple as using the [`open`](https://crates.io/crates/open) crate to open the generated `index.html` file.

**Comment by Br1oP** [comment]
That's a great idea. It will be a really nice add to the program, plus it is simple to implement. We should had thought about it before!

**Comment by Razican** [comment]
@Br1oP it would only be adding one option to the `Config` class, and parsing it with `clap` the same way we do with the other flags. Then, after generating the report, we only need to open it using the library I mentioned. I added the [`Hacktoberfest`](https://github.com/SUPERAndroidAnalyzer/super/labels/Hacktoberfest) label if somebody wants to implement it themselves, if not, we can do it on the first week of November :laughing:
