### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#67]
We should have a changelog so that we can keep track of the new features and bug fixes foe each new version.

**Comment by Br1oP** [comment]
I agree. I think it should be in MarkDown, a simple CHANGELOG.md. We should specify the format. I am thinking of the following one, tell me what do you think:

# VERSION - DATE
- Enhancements
  - a
  - b
- Bug Fixes
  - d
  - e
- Contributions
  - g
  - h

**Comment by aomader** [comment]
Check out `clog` in combination with angular's commit style guidelines, safes a lot of work.

**Comment by Razican** [comment]
We finally decided that it's easier to maintain simple/non-styled commits and write small and easy to read changelogs. We won't be writing big changelogs in 6 weeks, in any case ;)
