### ISSUE TITLE
Add tab completions

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#77]
Now that `clap` [has implemented](https://github.com/kbknapp/clap-rs/commit/3e36b0bac491d3f6194aee14604caf7be26b3d56) ZSH script generation, we should add those and add them to packages.

[Here](https://blog.clap.rs/complete-me/) an article on how to generate completions.

**Comment by panicbit** [comment]
I'll try to implement this :smile:

**Comment by panicbit** [comment]
#96 implements completion script generation.
Generation of ZSH completions is blocked by kbknapp/clap-rs#754.
The scripts still need to be packaged.

**edit:**
ZSH completion script generation is fixed now in clap 2.19 and is enabled via #97
