### ISSUE TITLE
Optional JSON/HTML reports

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#80]
Since there is currently no use for JSON reports, we should generate them only if the user requests them, by having a config variable in a config file (such as `json_report = true`) and also giving the option to add a `--json` flag to the program so that the JSON report is generated.

I've been thinking that the same could be done for HTML reports. By default, we would only generate HTML reports, but if `--json` flag is used or `json_report = true` is added to the config file, only JSON files should be generated (that way in automated environments no HTML files are generated). To generate both, both `--json` and `--html` flags should be used, or both `json_report = true` and `html_report = true` should be added to the config file.

What do you think?

**Comment by Br1oP** [comment]
I agree with you, it should be an optional feature. No reason to generate a JSON for every report since it won't be used in most cases.

**Comment by Chuky9** [comment]
Issue closed!!
