### ISSUE TITLE
Add SDK version strings

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#81]
We currently show SDKs as version 15, 17, 23 etc. We should also add version information such as "KitKat", "Lollipop" etc.

**Comment by Br1oP** [comment]
These links might help:
https://source.android.com/source/build-numbers.html
https://developer.android.com/reference/android/os/Build.VERSION_CODES.html

**Comment by Razican** [comment]
Moving this to SUPER 0.5.0.

**Comment by Cxarli** [comment]
Could you please tell me where these SDK numbers are printed? I can't seem to find them

**Comment by Razican** [comment]
Hi! sure,

In the templates, the code to show the SDK versions is in [`templates/super/report.hbs` lines 21 - 22][template_link]. The information gets serialized to the template in [`src/results/mod.rs` lines 307 - 311][serialize_link]. In this case, you will probably want to serialize a new element, something like `sdk_string`, that would be the codename of the version number.

A clean option would be to stop using a `u32` as a SDK version and start using an `enum` that can be parsed from an integer in the released versions, and that has an `as_str()` method that shows the codename. Something similar to what we do with [permissions in the manifest][permissions].

[template_link]: https://github.com/SUPERAndroidAnalyzer/super/blob/master/templates/super/report.hbs#L21-L22
[serialize_link]: https://github.com/SUPERAndroidAnalyzer/super/blob/master/src/results/mod.rs#L307-L311
[permissions]: https://github.com/SUPERAndroidAnalyzer/super/blob/master/src/static_analysis/manifest.rs#L2664
