### ISSUE TITLE
Verbose mode shows a lot of output from report generation

### ISSUE THREAD

**Issue by Razican** [SUPERAndroidAnalyzer/super#98]
Seems that since we merged #95 we are outputting a lot of "Debug" messages from the handlebars template generation in verbose mode.

**Comment by gnieto** [comment]
Sorry about that!
I will work on a fix for it this week, if you agree.
Maybe it was not the best idea to use the logger for this kind of reporting...

**Comment by Razican** [comment]
Sure, thanks!
